

SIMULATION_STEP = 1.024
# Basically, each treshold is multiplied by this value
TOLERANCE_MARGIN = 1.1

DYNAMIC_MAX_BUFFER_HEIGHT_SIZE = 128
DYNAMIC_MAX_BUFFER_HEIGHT_UPDATE_RATE = 8

DYNAMIC_MAX_BUFFER_FOV_WIDTH_SIZE = 16
DYNAMIC_MAX_BUFFER_FOV_WIDTH_UPDATE_RATE = 128

DYNAMIC_MAX_BUFFER_SPACECRAFT_VELOCITY_SIZE = 64
DYNAMIC_MAX_BUFFER_SPACECRAFT_VELOCITY_UPDATE_RATE = 64

MONGO_PUSH_BATCH_SIZE = 256

SIM_STATE_DUMP_INTERVAL = 5 # 60

